// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4e7e9f18df19dcd89141fcab537faf96)
declare namespace Cloudflare {
	interface Env {
		WORKER_SIG_KEY: string;
	}
}
interface Env extends Cloudflare.Env {}
