/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 37ac478a5e54a8ecbbf26b61e9db5832)
interface __BaseEnv_Env {
	WORKER_SIG_KEY: string;
	TARBALL_ENC_KEY: string;
	PACKAGES_BUCKET: R2Bucket;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
